### ISSUE TITLE
Missing error handling in Example 7 -> create Eample 7a

### ISSUE THREAD

**Issue by Petikoch** [Petikoch/Java_MVVM_with_Swing_and_RxJava_Examples#3]
As @mikebaum told me, but I didn't realize... The BehaviourSubject's are vulnerable to accidentially be terminated.

Let's look at `Example_7_ViewModel`:

```
    public void connectTo(final Example_7_Model model) {
        model.getLogs().subscribe(vm2v_log);
    }
```

As soon as the Observable from `model.getLogs()` publishes an error, the `model.getLogs()` Observable is "terminated" (kind of completed) and won't send any more items. Since we did directly subscribe using `subscribe(vm2v_log)` without any further handling, the `vm2v_log` will be terminated, too. We won't see any more log lines in our View, the View will we "dead".

Well... of course one can argument that the `model.getLogs()` Observable may not publish error's and the implementation of the Model is "buggy": "It's their fault!". Well, why not add some resilience here in the `Example_7_ViewModel` and create Example 7a?

**Comment by Petikoch** [comment]
I added example 7a with some exception handling in the ViewModel:

```
    public void connectTo(final Example_7a_Model model) {
        model.getLogs()
                .doOnError(throwable -> vm2v_log.onNext(new LogRow("!", "Unexpected error -> will retry here in ViewModel", "Error: " + throwable.getMessage())))
                .retry(5)
                .onErrorReturn(throwable -> new LogRow("!!!", "Too many unexpected errors -> stop", "Error: " + throwable.getMessage()))
                .subscribe(vm2v_log);
    }
```

This doesn't answer the question of the _"BehaviourSubject's are vulnerable to accidentially be terminated"_. But opens some new questions. Should a ViewModel property be terminateable at all? How resilient should the ViewModel be against issues in the Model? Where do you put that error resilience? In the Model or in the ViewModel?

**Comment by mikebaum** [comment]
@Petikoch I'm a little bit busy right now... but I'm very interested in discussing this. I'll get back to you within a day or two... :)

**Comment by mikebaum** [comment]
So I've had a quick look at your example...

In the code I currently have in production that I committed at work, I never connect two properties on the error and complete events, so rather I bind properties as follows:

``` java
BehaviorSubject<String> property1 = BehaviorSubject.create();
BehaviorSubject<String> property2 = BehaviorSubject.create();
property1.subscribe(property2::onNext);
```

When it comes to lifetime, I make all my models extends Destroyable, i.e.:

``` java
public interface Destroyable {
        void destroy();
}

public class ViewModel implements Destroyable {

    private final BehaviorSubject<String> property1 = BehaviorSubject.create();

    @Override
    public void destroy() {
        property1.onCompleted();
    }

    public BehaviorSubject<String> getProperty1() {
        return property1;
    }
}
```

As for errors, if they are important I create a specific stream to emit just the exceptions that occurred. The only place I do this now is in an instances of an `RxCommand`, which is very similar to the `ReactiveCommand` object as detailed in ReactiveUI. For, example:

``` java
public class Command<I, R> {

    private final BehaviorSubject<R> results = BehaviorSubject.create();
    private final BehaviorSubject<Throwable> exceptions = BehaviorSubject.create();
    private final Func1<I, Observable<R>> asyncFunc;

    public Command(Func1<I, Observable<R>> asyncFunc) {
         this.asyncFunc = asyncFunc;
    }

    public Observable<R> getResults() {
        return results;
    }

    public Observable<Throwable> getExceptions() {
        return exceptions;
    }

    public void execute(I input) {
        asyncFunc.call(input).subscribe(results::onNext, exceptions::onNext);
    }
}
```

Clearly that Command class is lacking, specifically it would be good to have yet another property that emits status, i.e. Idle, Executing, Finished, Failed, etc... Also, it would be possible to get rid of the input from the execute method by wiring up the command to an input observable. Also, the command should emit a property "isEnabled". Anyway, I'm getting carried away.

In general I have come to the conclusion that the onError events only make sense in places where you know that something could fail (most of the time IO). For normal properties that have replaced mutable fields, the onError makes no sense. Yes, you can have a RuntimeException, but this is normally a programmer error and should be caught before shipping the code to a client. So I never subscribe one subject to another on all events. In fact in the library I'm working on I don't even offer an Error event stream on properties, only onChanged and onDisposed. Anyway, that's my two cents....

**Comment by Petikoch** [comment]
Thanks @mikebaum for your thoughts and your feedback.
